### ISSUE TITLE
buildRequestUrl() rounds latitude and longitude to 6 digits of precision

### ISSUE THREAD

**Issue by brownoxford** [shawntoffel/darksky#15]
The buildRequestUrl() function uses `%f` formatting to build the URL using the provided latitude and longitude. This causes the given values to be rounded to the default six digits of precision for `%f`.

While weather is likely to be accurate with six digits, this resulting response from DarkSky will contain a different value for lat/lng than what was given by the user. This could result in problems with other integrated systems that require position to be stored with a higher degree of precision.

A possible solution would be to change this to use `%.8g` formatting, which will allow up to 8 digits of precision (while still truncating trailing zeroes). This is accurate to 1.1132 mm [according to Wikipedia](https://en.wikipedia.org/wiki/Decimal_degrees)

**Comment by shawntoffel** [comment]
Thanks! I don't have any docs saying this for certain, but test data seems to suggest that the API rounds latitude and longitude to only 4 decimal places regardless of what is provided. I may be wrong there.  (Edit: I was wrong. The API does in fact return all digits)

That said, I think I'm of the mind that this client shouldn't be responsible for rounding of user input and any rounding that occurs should come from the API. I'm almost okay with adjusting the float to string conversion to allow all 64 bits of the float64.

**Comment by brownoxford** [comment]
hmm. That might be the case on the back-end, but in my testing the API does return the values that were presented to it without rounding or truncating.

I ran into this issue when storing results using the lat/lon in the response and then trying to correlate with my own source records for each location - it was easy enough to work around by overwriting the response data with my source location data before storing it, but it was definitely unexpected to have that round-trip corruption.

**Comment by brownoxford** [comment]
Also: agreed on `%g` instead of `%.8g`

**Comment by shawntoffel** [comment]
Release v1.3.0 onward will use `%g`. If there end up being any issues with it feel free to re-open this issue. Thanks!
