### ISSUE TITLE
DataPoint is missing min/max temperature fields

### ISSUE THREAD

**Issue by brownoxford** [shawntoffel/darksky#16]
The following fields are missing from the DataPoint structure:

- apparentTemperatureMax
- apparentTemperatureMaxTime
- apparentTemperatureMin
- apparentTemperatureMinTime
- temperatureMax
- temperatureMaxTime
- temperatureMin
- temperatureMinTime

**Comment by shawntoffel** [comment]
Interesting. These fields were removed in https://github.com/shawntoffel/darksky/pull/11 as they had been  "deprecated" in the docs. After a quick peak it looks like the deprecated note has been removed for these fields. I have no issue with adding them back in.
